### ISSUE TITLE
Whois Lookup

### ISSUE THREAD

**Issue by mehrdad2** [hitechSense/hitechSense-website#5]
add whois lookup to REGISTER DOMAIN NAME page.

**Comment by shimafaraji** [comment]
Done

**Comment by mehrdad2** [comment]
<img width="1440" alt="screen shot 2018-05-14 at 12 00 12 am" src="https://user-images.githubusercontent.com/4264683/39971039-dac89bbc-5709-11e8-85e0-b447ab321230.png">
