### ISSUE TITLE
new website structure 

### ISSUE THREAD

**Issue by sepidearaghi** [hitechSense/hitechSense-website#6]
please set our website structure to same as file attachment.
[rivalrySiteStructure.pdf](https://github.com/rivalryweb/rivalryweb-website/files/2598872/rivalrySiteStructure.pdf)

**Comment by mehrdad2** [comment]
![services](https://user-images.githubusercontent.com/4264683/51567282-0fcfde00-1eac-11e9-98e9-15ac6fdd18de.png)
![home](https://user-images.githubusercontent.com/4264683/51567283-10687480-1eac-11e9-84f5-a5f90c896f91.png)
![about](https://user-images.githubusercontent.com/4264683/51567284-10687480-1eac-11e9-82a8-39b2aaf1de80.png)

**Comment by mehrdad2** [comment]
![home](https://user-images.githubusercontent.com/4264683/51694669-90125280-2016-11e9-8b99-296eefebf489.png)
